services:
  cc-mysql:
    image: mysql:9.2
    container_name: cardsCollec-db
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - cardsCollec-dbdata:/var/lib/mysql
    restart: unless-stopped
    networks:
      - default
      - pma_network

  cc-node:
    image: akuan09/cards-collec:latest
    container_name: cardsCollec-node
    depends_on:
      - cc-mysql
    environment:
      DB_HOST: ${MYSQL_HOST}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      PORT: ${NODE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cc-node.rule=Host(`cc-api.asd9.fun`)"
      - "traefik.http.routers.cc-node.tls.certresolver=letsencrypt"
      - "traefik.http.services.cc-node.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_network"
    networks:
      - default
      - traefik_network

volumes:
  cardsCollec-dbdata:

networks:
  default:
  pma_network:
    external: true
  traefik_network:
    external: true
